provider:
  name: faas
  gateway: http://127.0.0.1:31112
functions:
  upcoming-events:
    lang: node
    handler: ./upcoming-events
    image: padiazg/upcoming-events:latest
    environment:
      content_type: text/html
